### ISSUE TITLE
Redeploy to pypi once stashy is updated

### ISSUE THREAD

**Issue by noahp** [noahp/stash-pr-stats#2]
Once stashy is updated, `stash-py-stats` should be able to be successfully deployed to pypi; at the moment since this package relies on a fork of stashy, we can only install from source, see:
> https://github.com/pypa/pip/issues/5566#issuecomment-402417467

See these issues for the stashy update:
> https://github.com/cosmin/stashy/issues/109
> https://github.com/cosmin/stashy/pull/111

Note- this is enforced by pypi with the error when publishing:
```bash
HTTPError: 400 Client Error: Invalid value for requires_dist. Error: Can't have direct dependency: 'stashy @ git+https://github.com/noahp/stashy.git@f42707cb87fe7a50f77d739b00494720062fd06e' for url: https://upload.pypi.org/legacy/
```

**Comment by cosmin** [comment]
I just pushed `stashy` 0.6 to PyPI, sorry for the long delay my job took a long detour from dealing with Python and with the changes to PyPI.org and Twine I never quiet got around to updating my setup to push new releases.
